name: Weekly Movie Update

on:
  schedule:
    - cron: "0 7 * * 1" 
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run main.py
        run: python main.py

      - name: Ensure Git is installed
        run: sudo apt-get update && sudo apt-get install -y git

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add changes to Git
        run: git add movie.json

      - name: Commit changes if any
        run: |
          git diff --cached --quiet || git commit -m " Haftalık film güncellemesi"
          git diff --cached --quiet && git commit --allow-empty -m "📌 Keep-alive commit"

      - name: Push changes to GitHub
        run: |
          git pull --rebase origin main 
          git push
