name: Weekly Movie Update

on:
  schedule:
    - cron: '0 7 * * 1'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run main.py
        run: python main.py

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Debug print token length
        run: |
          echo "Token length: ${#TOKEN}"
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
          
      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:$TOKEN@github.com/${{ github.repository }}.git
          git add movie.json
          git diff --cached --quiet || git commit -m "🔄 Haftalık film güncellemesi"
          git push origin HEAD:main
